ARG NODE_VERSION=20.10.0
FROM node:${NODE_VERSION}-slim AS dev

WORKDIR /app
ENV NODE_ENV="development"

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Instala ferramentas úteis para desenvolvimento
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3 curl git && \
    rm -rf /var/lib/apt/lists/*

# Copia apenas os arquivos de dependência para cache de instalação
COPY package.json package-lock.json* ./

# Instala todas as dependências (incluindo devDependencies)
RUN npm install

# Copia o restante da aplicação
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 3000

CMD ["tail", "-f", "/dev/null"]
