services:
  web:
    container_name: df_sistemas_web_dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        VITE_API_URL: "http://localhost:3333/v1"
    ports:
      - "3000:3000"
  api:
    container_name: df_sistemas_api_dev
    restart: on-failure
    build:
      context: ./server
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/products_db?authSource=admin
    ports:
      - "3333:3333"
    depends_on:
      - mongo
  mongo:
    container_name: df_sistemas_mongo_dev
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data_dev:/data/db

volumes:
  mongo_data_dev:
